app_shop_index:
    path:     ""
    defaults: { _controller: AppBundle:Shop:index }

app_shop_cart:
    path:     /cart
    defaults: { _controller: AppBundle:Shop:cart }

app_shop_image:
    path:     /image/{imageId}
    defaults:
        _controller: AppBundle:Shop:image
    requirements:
        imageId: \d+

app_shop_category:
    path:     /{categorySlug}
    defaults:
        _controller: AppBundle:Shop:category
    requirements:
        categorySlug: "[a-z0-9-]+"

app_shop_product:
    path:     /{categorySlug}/{productSlug}
    defaults:
        _controller: AppBundle:Shop:product
    requirements:
        categorySlug: "[a-z0-9-]+"
        productSlug: "[a-z0-9-]+"
