app_security:
    resource: routing/security.yml

app_page:
    resource: routing/page.yml

app_shop:
    prefix: /shop
    resource: routing/shop.yml

app_admin:
    prefix: /admin
    resource: routing/admin.yml
