app_home:
    path:     /
    defaults: { _controller: AppBundle:Page:index }


app_contact:
    path:     /contact
    defaults: { _controller: AppBundle:Page:contact }

app_shop:
    prefix: /shop
    resource: routing/shop.yml

app_admin:
    prefix: /admin
    resource: routing/admin.yml

app_product:
    resource: "routing/product.yml"
    prefix:   /admin/product
