parameters:
    image_directory: '%kernel.root_dir%/../var/data/image'

services:
    app.upload.image_uploader:
        class: AppBundle\Upload\Uploader
        arguments: ['%image_directory%']

    app.event_listener.image:
        class: AppBundle\EventListener\ImageEventListener
        arguments: ['@app.upload.image_uploader']
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preUpdate }
            - { name: doctrine.event_listener, event: postRemove }

    app.twig.shop_extension:
        class: AppBundle\Twig\ShopExtension
        arguments: ['@router']
        tags:
            - { name: twig.extension }

#    app.repository.product:
#        class: AppBundle\Repository\ProductRepository
#        factory: ['@doctrine.orm.default_entity_manager', getRepository]
#        arguments:
#            - AppBundle\Entity\Product
