AppBundle\Entity\Product:
    properties:
        title:
            - NotBlank: ~
        price:
            - GreaterThan: 0
        # Pour la validation du stock, voir la contrainte de classe :
        # src/AppBundle/Validator/Constraints/Product.php et
        # src/AppBundle/Validator/Constraints/ProductValidator.php
        #stock:
        #    - GreaterThanOrEqual: 0
        releasedAt:
            - NotBlank: ~
            - Type: \DateTime
        features:
            - Count:
                min: 1
        images:
            - Count:
                min: 1
        seo:
            - Valid: ~
        category:
            - Valid: ~
    constraints:
        - AppBundle\Validator\Constraints\Product: ~

AppBundle\Entity\Image:
    properties:
        alt:
            - NotBlank: ~

AppBundle\Entity\Seo:
    properties:
        title:
            - NotBlank: ~

AppBundle\Entity\User:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: username
    properties:
        username:
            - NotBlank: ~
            - Length:
                min: 3
    getters:
        isActive:
            - IsTrue: ~
