AppBundle\Entity\Image:
    type: entity
    table: image
    repositoryClass: AppBundle\Repository\ImageRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        file:
            type: string
            length: 255
        alt:
            type: string
            length: 255
            nullable: true
    manyToOne:
        product:
            targetEntity: AppBundle\Entity\Product
            inversedBy: images
            joinColumn:
                name: product_id
                referencedColumnName: id
            onDelete: CASCADE
